Map render
mve1983/catch-share-capstone-project pull request #9
Opened 2022-01-17 10:25 UTC by mve1983

see issue #7 

- click on map will open form to submit a catch
- cancel will delete the marker and set dorm data to initial
- confirm will send data to db and close form

-please ignore the uncaught promise log message, that's for the next userstory who provides the fetch of the data and render a card for the catch under the map
- code is a bit of a mess, needs refactoring and more components, will clarify in the next steps.

2022-01-17 17:42 UTC, anitaschiller requested changes
Hi Manuel, really cool form, many (complex) features. Next time when you realize that the pull request is getting waaay to big, it might be a good idea to split it into several PRs. But all i all really nice work!

2022-01-17 17:42 UTC, anitaschiller commented on client/src/components/Navbar.jsx
> +        <NavLink to="map">Karte</NavLink>
```suggestion
        <NavLink to="/map">Karte</NavLink>
```

2022-01-17 17:42 UTC, anitaschiller commented on client/src/components/Navbar.jsx
> +        <NavLink to="weather">Wetter</NavLink>
```suggestion
        <NavLink to="/weather">Wetter</NavLink>
```

2022-01-17 17:42 UTC, anitaschiller commented on client/src/components/catchCardForm/CatchForm.jsx
> +        break;
Is there an easier way to manage all these date parts?

2022-01-17 17:42 UTC, anitaschiller commented on client/src/components/catchCardForm/CatchForm.jsx
> +      <FormDivBorderStyling> </FormDivBorderStyling>
Could be self-closing :)

2022-01-17 17:42 UTC, anitaschiller commented on client/src/components/catchCardForm/CatchForm.jsx
> +              <u>Ihr Fang:</u>
Underline is better defined in CSS, with a `legend strong` or similar CSS rule set.

2022-01-17 17:42 UTC, anitaschiller commented on client/src/lib/catchFormArrays.js
> +];
Thomas would like to see "Dynamitfischen" as well ;)
```suggestion
const tackle = [
  "A n d e r e",
  "Grundangeln",
  "Spinnfischen",
  "Fliegenfischen",
  "Posenangeln",
  "Dynamitfischen"
];
```

2022-01-17 17:42 UTC, anitaschiller commented on package.json
> +    "@uppy/tus": "^2.2.0"
Are you sure that these should be placed in the outer package.json?

2022-01-17 17:42 UTC, anitaschiller commented on server/models/catchCard.model copy.js
> +export default CatchCard;
Can be deleted!

2022-01-18 03:55 UTC, mve1983 commented on client/src/components/catchCardForm/CatchForm.jsx
> +        break;
Currently not. but is on my list for refactoring. :)
The date for the catch should be saved as string, not as date object in the database. This is because of reasons for other user stories later. ;) 
As my own build date picker has Day, Month, Year and Time as values I have to change every value on user input change in a string. 
With refactoring for Map page I will work on this for sure, for now I will leave it as a "make it work solution".

2022-01-18 03:56 UTC, mve1983 commented on client/src/components/catchCardForm/CatchForm.jsx
> +      <FormDivBorderStyling> </FormDivBorderStyling>
Yes, changed.

2022-01-18 04:03 UTC, mve1983 commented on client/src/lib/catchFormArrays.js
> +];
Sorry, but nope. ;)

2022-01-18 04:09 UTC, mve1983 commented on client/src/components/catchCardForm/CatchForm.jsx
> +              <u>Ihr Fang:</u>
You mean the underline <u> tag, right? That's better defined in CSS by text-decoration: underline. 
Because you wrote it's better defined by _legend strong_? The strong I want to keep, because it's better for accessibility than a font-weight: bold in CSS.

2022-01-18 04:11 UTC, mve1983 commented on package.json
> +    "@uppy/tus": "^2.2.0"
Ahh yes, installed them wrong and also uninstalled the from that folder. Obviously the uninstall did not delete the dependencies in package.json, for hatever reason.
Delete them by hand now. Thanks.

2022-01-18 04:13 UTC, mve1983 commented on server/models/catchCard.model copy.js
> +export default CatchCard;
Right, deleted. Thanks.

2022-01-18 04:35 UTC, mve1983 commented
Thanks for the review. Yes, I realized it was big after it was too big. :) 
Also a learning process and I now know I have split user stories even if it's only "one simple" form. :)

2022-01-18 04:35 UTC, merged